# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:26:27+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Message(BaseModel):
    content: str
    from_: str = Field(..., alias='from')
    to: List[str] = Field(..., description='Destination Number')


class SendSMSRequest(BaseModel):
    content: str = Field(..., description='Message Content')
    from_: str = Field(..., alias='from', description='Sender ID / Number')
    to: int = Field(..., description='Destination Mobile Number')


class BulkSMSRequest(BaseModel):
    messages: List[Message] = Field(..., description='Sendbatch message body')
